services:
  generator:
    build:
      context: ..
      dockerfile: docker/generator.Dockerfile
      args:
        BINARY_PATH: /app/bin
        API_KEY: $ASTRA_API_KEY
        ENABLE_CONCURRENCY: $ENABLE_CONCURRENCY
    environment:
      GENERATOR_DATA_PATH: "/data/generator"
      SIMULATION_DATA_PATH: "/data/simulation"
    volumes:
      - data:/app/data
    networks:
      - astra
    restart: unless-stopped

volumes:
  data:

networks:
  astra:
    driver: bridge