services:
  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
      args:
        BINARY_PATH: /opt/astra #/usr/local/bin
        API_KEY: $ASTRA_API_KEY
    environment:
      GENERATOR_DATA_PATH: "/data/generator"
      SIMULATION_DATA_PATH: "/data/simulation"
    volumes:
      - data:/app/data
    networks:
      - astra
    restart: unless-stopped

volumes:
  data:

networks:
  astra:
    driver: bridge