services:
  api:
    build:
      args:
        ENABLE_CONCURRENCY: true
    environment:
      SERVER_ROOT_PATH: "/astra"
    deploy:
      replicas: 5

  nginx:
    container_name: nginx
    build:
      context: ..
      dockerfile: docker/nginx.Dockerfile
    networks:
      - astra
    depends_on:
      - api
    ports:
      - "80:80"
    restart: unless-stopped