services:
  generator:
    container_name: generator
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        PYTHON_VERSION: 3.12
        ASTRA_GENERATOR_BINARY_PATH: /app/bin/generator
        SERVER_ROOT_PATH: /astra/generator
        API_KEY: $ASTRA_API_KEY
    volumes:
      - data:/app/data
      - config:/app/config
    networks:
      - astra
    expose:
      - "8000"
    restart: unless-stopped
    
volumes:
  data:
  config:

networks:
  astra:
    driver: bridge