services:
  generator:
    build:
      args:
        ENABLE_CONCURRENCY: True
    environment:
      SERVER_ROOT_PATH: "/astra"

  nginx:
    container_name: nginx
    build:
      context: ..
      dockerfile: docker/nginx.Dockerfile
    networks:
      - astra
    depends_on:
      - generator
    ports:
      - "80:80"
    restart: unless-stopped