services:
  generator:
    build:
      context: ..
      dockerfile: docker/generator.Dockerfile
      args:
        PYTHON_VERSION: 3.12
        BINARY_PATH: /app/bin
        API_KEY: $ASTRA_API_KEY
    environment:
      GENERATOR_DATA_PATH: "/data/generator"
      SIMULATION_DATA_PATH: "/data/simulation"
    volumes:
      - data:/app/data
    networks:
      - astra
    restart: unless-stopped

volumes:
  data:

networks:
  astra:
    driver: bridge